
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'User2_Record_Status_Type')
CREATE TABLE [DBO].[User2_Record_Status_Type] (
	[ID] [int] IDENTITY (1, 1) NOT NULL,
	[UserID] Int,
	[RecordStatusTypeID] Int NULL,
) ON [PRIMARY]

--PRIMARY KEY
IF NOT EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[PK_User2_Record_Status_Type_ID]')
	AND OBJECTPROPERTY(ID, N'IsPrimaryKey') = 1)
ALTER TABLE [DBO].User2_Record_Status_Type WITH NOCHECK ADD 
	CONSTRAINT [PK_User2_Record_Status_Type_ID] PRIMARY KEY CLUSTERED ([ID])  ON [PRIMARY]
GO

--FOREIGN KEY

IF NOT EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID= OBJECT_ID(N'[DBO].[FK_User2_Record_Status_Type_UserID]')
	AND OBJECTPROPERTY(ID, N'IsForeignKey') = 1)
ALTER TABLE [DBO].[User2_Record_Status_Type] ADD CONSTRAINT [FK_User2_Record_Status_Type_UserID] FOREIGN KEY
	([UserID]) REFERENCES [DBO].[User2] ([ID])
