IF NOT EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME IN ('UserID') AND TABLE_NAME IN ('Batch_Record'))
	ALTER TABLE DBO.[Batch_Record] Add UserID int NULL
GO

--FOREIGN KEY
IF NOT EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID= OBJECT_ID(N'[DBO].[FK_Batch_Record_UserID]')
	AND OBJECTPROPERTY(ID, N'IsForeignKey') = 1)
ALTER TABLE [DBO].Batch_Record ADD CONSTRAINT [FK_Batch_Record_UserID] FOREIGN KEY
	([UserID]) REFERENCES [DBO].[User2] ([ID])
GO

IF NOT EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME IN ('UserID') AND TABLE_NAME IN ('Case2'))
	ALTER TABLE DBO.[Case2] Add UserID int NULL
GO

--FOREIGN KEY
IF NOT EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID= OBJECT_ID(N'[DBO].[FK_Case2_UserID]')
	AND OBJECTPROPERTY(ID, N'IsForeignKey') = 1)
ALTER TABLE [DBO].Case2 ADD CONSTRAINT [FK_Case2_UserID] FOREIGN KEY
	([UserID]) REFERENCES [DBO].[User2] ([ID])
GO

IF NOT EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME IN ('StateID') AND TABLE_NAME IN ('County'))
	ALTER TABLE DBO.[County] Add StateID int NULL
GO

--FOREIGN KEY
IF NOT EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID= OBJECT_ID(N'[DBO].[FK_County_StateID]')
	AND OBJECTPROPERTY(ID, N'IsForeignKey') = 1)
ALTER TABLE [DBO].County ADD CONSTRAINT [FK_County_StateID] FOREIGN KEY
	([StateID]) REFERENCES [DBO].[State_Type] ([ID])
GO

IF NOT EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME IN ('StateID') AND TABLE_NAME IN ('Batch_Record'))
	ALTER TABLE DBO.[Batch_Record] Add StateID int NULL
GO

--FOREIGN KEY
IF NOT EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID= OBJECT_ID(N'[DBO].[FK_Batch_Record_StateID]')
	AND OBJECTPROPERTY(ID, N'IsForeignKey') = 1)
ALTER TABLE [DBO].Batch_Record ADD CONSTRAINT [FK_Batch_Record_StateID] FOREIGN KEY
	([StateID]) REFERENCES [DBO].[State_Type] ([ID])
GO

IF NOT EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME IN ('UserID') AND TABLE_NAME IN ('Record_Case'))
	ALTER TABLE DBO.[Record_Case] Add UserID int NULL
GO

--FOREIGN KEY
IF NOT EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID= OBJECT_ID(N'[DBO].[FK_Record_Case_UserID]')
	AND OBJECTPROPERTY(ID, N'IsForeignKey') = 1)
ALTER TABLE [DBO].Record_Case ADD CONSTRAINT [FK_Record_Case_UserID] FOREIGN KEY
	([UserID]) REFERENCES [DBO].[User2] ([ID])
GO

UPDATE BATCH_RECORD 
SET STATEID = 6
WHERE STATEID IS NULL 


UPDATE Company  
SET STATEID = 6
WHERE STATEID IS NULL 
